"""empty message

Revision ID: c9079136752e
Revises: 
Create Date: 2020-04-09 19:21:26.255637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9079136752e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normal_user', sa.Column('lng', sa.Numeric(precision=10, scale=6), nullable=True))
    op.alter_column('normal_user', 'lat',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.drop_column('normal_user', 'long')
    op.alter_column('slot', 'merchant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'slot', 'Merchant', ['merchant_id'], ['merchant_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.alter_column('slot', 'merchant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('normal_user', sa.Column('long', sa.VARCHAR(), nullable=True))
    op.alter_column('normal_user', 'lat',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('normal_user', 'lng')
    # ### end Alembic commands ###
